default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: mise-pre-commit
        name: Run mise pre-commit
        entry: mise pre-commit
        language: shell
